name: Terraform Deployment

on:
  push:
    branches:
      - main # תריץ רק כשדוחפים שינויים ל-main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Create .env File
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}"
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" 
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}"
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}"
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}"

      # 3. Export environment variables (to make them available for Terraform)
      - name: Export Environment Variables
        run: |
          export $(cat project/.env | xargs)  

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Validate Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TF_VAR_mysql_database: ${{ secrets.MYSQL_DATABASE }}
          TF_VAR_mysql_user: ${{ secrets.MYSQL_USER }}
          TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
          TF_VAR_mysql_host: ${{ secrets.MYSQL_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Apply Terraform configuration (optional, זה מבצע את ה-apply בפועל)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TF_VAR_mysql_database: ${{ secrets.MYSQL_DATABASE }}
          TF_VAR_mysql_user: ${{ secrets.MYSQL_USER }}
          TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
          TF_VAR_mysql_host: ${{ secrets.MYSQL_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

